# Generated by Django 3.2 on 2023-07-11 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ride',
        ),
    ]
